import './globals.css'
import { Inter } from 'next/font/google'
// import 'react-date-range/dist/styles.css'; 
// import 'react-date-range/dist/theme/default.css';
import "mapbox-gl/dist/mapbox-gl.css";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
